filter="udp"			color="proto:VIOLET"				cont 
filter="tcp"			color="saddr,daddr,proto:WHITE"			cont
filter="tcp and port http" 	color="dport:GREEN"				cont
filter="tcp"			color="sport:BLUE+DIM"				cont
filter="dst port domain" 	color="dport:CYAN+DIM"				cont
filter="dst port imaps"      	color="dport:MAGENTA+DIM"			cont 
filter="src pkts gt 50"		color="spkts,dpkts,sbytes,dbytes:RED+BLINK" 
filter="src co CN"		color="all:RED+BLINK"
