# Set TERM for colors
set -g default-terminal "screen-256color"

# Use vi keybindings
set-window-option -g mode-keys vi

# Change bindings for window splits
bind \ split-window -h
bind - split-window -v

# Add bindings to navigate panes with vi move keys
bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R

# Add bindings to resize panes with vi move keys
bind -r M-k resize-pane -U 5
bind -r M-j resize-pane -D 5
bind -r M-h resize-pane -L 5
bind -r M-l resize-pane -R 5
