#!/usr/bin/env sh

# Charles H. Leggett's yabairc
# There are many like it, but this one is mine.

# Load Scripting Addition
## must run 'sudo yabai --install-sa' after install of yabai
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# Windows are tiled with "binary space partitioning"
yabai -m config layout bsp

# on or off (default: off)
yabai -m config auto_balance on

# New window spawns to the right if vertical split, or bottom if horizontal split
yabai -m config window_placement second_child

# window border
yabai -m config window_border on
yabai -m config window_border_width 6
yabai -m config active_window_border_color 0xff689D6A
yabai -m config normal_window_border_color 0xff282828

# window opacity (default: off)
# This doesn't work yet on Apple Silicon
yabai -m config window_opacity on
yabai -m config active_window_opacity 0.8
yabai -m config normal_window_opacity 0.5

# set focus follows mouse mode (default: off, options: off, autoraise, autofocus)
#yabai -m config focus_follows_mouse autoraise

# set mouse follows focus mode (default: off)
#yabai -m config mouse_follows_focus on

# floating windows are always on top (default: off)
#yabai -m config window_topmost on

# float system preferences
yabai -m rule --add app="^1Password$" manage=off
yabai -m rule --add app="^Alfred\ Preferences$" manage=off
yabai -m rule --add app="^Cisco\ AnyConnect.*$" manage=off
yabai -m rule --add app="^Dictionary$" manage=off
yabai -m rule --add app="^Speedtest$" manage=off
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^Wally$" manage=off

